config/routes.rb
Rails.application.routes.draw do
  get '/etsy_search', to: 'etsy#search'
  root 'etsy#search'
end

app/models/search.rb
class Search < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/etsy_controller.rb
class EtsyController < ApplicationController

  # GET /etsy_search => etsy#search
  # EX: localhost:3000/etsy_search?q=whiskey
  def search
    Etsy.api_key = ENV['ETSY_API_TOKEN']

    search_results =  Etsy::Request.get(
      '/listings/active',
      :includes => ['Images', 'Shop'],
      :keywords => params[:q],
      :category => params[:c]
    )

    @listings = JSON.parse(search_results.body)['results']
    @categories = EtsyController::all_categories
    # binding.pry
    render :search
  end

  def self.all_categories
    categories = Etsy::Category.all_top
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  ETSY_API_TOKEN = ENV['ETSY_API_TOKEN']
  # ETSY_API_TOKEN = kn84tew7pjzr6upsxq0m864t
  # SECRET = va4dv3nqsl
  # GET /etsy_search => etsy#search
  # GET /etsy_search
  def search
    search_results =  Etsy::Request.get('/listings/active',
                                        :includes => ['Images', 'Shop'],
                                        :keywords => 'whiskey')
    @to_ruby = JSON.parse(search_results.body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/etsy/search.html.erb
<header class='site-border'>
  <div class='logo-nav-top float-left'>
    <%=link_to image_tag('https://s3.amazonaws.com/siteassets.etsy.com/press/Website/etsy-logo.png',{id: 'logo'}), '/?ref=lgo'%>
  </div>
  <div class='form-container float-left'>
    <%= form_tag('/etsy_search', method: 'get', class:'form-container-inner') do %>
      <div class='text-field-wrapper'>
        <%= text_field_tag(:q, params[:q], class: 'text-field', placeholder: 'Search for items or shops') %>
      </div>
      <div class='submit-wrapper'>
        <button type='submit' value='Search' class='submit-button'>Search</button>
      </div>
    <% end %>
  </div>

  <ul class='nav-menu float-right'>
    <li class="float-left"><%=link_to 'Sell on Etsy', "https://www.etsy.com/sell?ref=hdr&amp;from_page=https%3A%2F%2Fwww.etsy.com%2Fsearch", {id:'sell'}%></li>
    <li class="float-left"><%=fa_icon 'home'%><span class="nav-text">Home</span></li>
    <li class="float-left"><%=fa_icon 'heart'%><span class="nav-text">Favorites</span></li>
    <li class="float-left"><%=fa_icon 'user'%><span class="nav-text">You</span></li>
    <li class="float-left"><%=fa_icon 'shopping-cart'%><span class="nav-text">Cart</span></li>
  </ul>
</header>

<div class='content'>
  <div class="sidebar float-left">
    <h5 class="content-heading text-grey">Show results for:</h5>
      <div class='sidebar-category'>
        <ul class='list-unstyled'>
          <li class='strong list-category-bottom'><%=link_to 'All categories', etsy_search_path(q: params[:q]), {class: 'text-grey'}%></li>
          <% @categories.each do |category| %>
          <%result = category.result%>
            <li class='list-category-left list-category-bottom'><%=link_to result['short_name'], etsy_search_path(q: params[:q], c: result['name'])%></li>
          <% end %>
        </ul>
      </div>
    <h5 class="content-heading text-grey">Refine your search</h5>
    <div class='sidebar-category'></div>
  </div>

  <div class='content-listing float-right'>
    <div class="content-heading text-grey padding-heading">
      <%=link_to 'All categories', etsy_search_path(q: params[:q])%>
      <%=fa_icon 'chevron-right'%>
      <%if params[:q]%>
        <span class="strong">“<%=params[:q]%>”</span>
      <%end%>
      <span>(<%=@listings.count%> Results)</span>
    </div>
    <table>
      <% @listings.in_groups_of(4, false) do |listing| %>
        <tr>
          <% for l in listing %>
            <td>
              <div class ='card'>
                <%next if l['Images'].nil?%>
                <%=link_to image_tag(l['Images'][0]['url_170x135'], alt: l['Images'][0]['listing_image_id'], size: '244x206'), l['url']%>
                <div class='listing-details'>
                  <div class= 'listing-desc'>
                    <%=l['title']%>
                  </div>
                  <div class= 'card-shop-name'>
                    <%=l['Shop']['shop_name']%>
                  </div>
                  <div class='card-price float-right'>
                    <%=number_to_currency l['price']%>
                  </div>
                </div>
              </div>
            </td>
          <% end %>
        </tr>
      <% end %>
    </table>
  </div>
</div>

<footer class='site-border'></footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EtsySearcher</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/searches/search.html.erb
<header class="site_border">

  <div class="logo_nav_top">
    <img src="https://s3.amazonaws.com/siteassets.etsy.com/press/Website/etsy-logo.png"/>
  </div>
  <div class="form_container">
      <div class="form_container_inner">
        <div class="text_field">
        </div>
        <div class="submit">
        </div>
      </div>
  </div>

  <ul>
    <li>Home</li>
    <li>Favorites</li>
    <li>Cart</li>
  </ul>

</header>

<div class = "content">
  <div class = "side_nav"></div>
  <div class = "listing"></div><div class = "listing"></div><div class = "listing"></div>
  <div class = "listing"></div><div class = "listing"></div><div class = "listing"></div>
  <div class = "listing"></div><div class = "listing"></div><div class = "listing"></div>
  <div class = "listing"></div><div class = "listing"></div><div class = "listing"></div>
  <div class = "listing"></div><div class = "listing"></div><div class = "listing"></div>
  <div class = "listing"></div><div class = "listing"></div><div class = "listing"></div>
</div>


<footer class="site_border"></footer>